name: Deploy Site Latest Changes

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up SSH
        uses: webfactory/ssh-agent@v0.8.0

        with:
          ssh-private-key: ${{ secrets.DEPLOY_SERVER_KEY }}

      - name: Deploy Application
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.DEPLOY_SERVER_USER }}@${{ secrets.DEPLOY_SERVER_IP }} << 'EOF'
          set -x
          cd ${{ secrets.DEPLOY_SERVER_DIR }}
          git reset --hard HEAD
          git clean -df
          git pull origin master
          composer install --no-interaction --prefer-dist --no-dev --optimize-autoloader
          php artisan migrate --force
          php artisan optimize:clear
          php artisan route:cache
          php artisan config:clear
          EOF
